@startuml

!theme cloudscape-design
skinparam BackgroundColor lightgray

alt using machine provider
alt machine doesn't exist
Devsy -> Provider: devsy machine create
Provider --> Devsy: machine id
end
Devsy -> Provider: devsy machine start
Provider --> Devsy: machine id
end

Devsy -> Repo: git pull
Repo --> Devsy: source code

alt image not already available
Devsy -> Agent: devsy workspace build
activate Agent
Agent --> ContainerRuntime: build
ContainerRuntime --> Agent: image
Agent --> Devsy:
deactivate Agent
end

Devsy -> Agent: devsy helper ssh-server --stdio
activate Agent
Devsy -> Agent: devsy agent daemon
Devsy -> Agent: devsy agent workspace up --workspace-info

Agent -> ContainerRuntime: run
ContainerRuntime --> Agent: container id

Agent -> ContainerAgent: devsy helper ssh-server --stdio
activate ContainerAgent

Agent -> ContainerAgent: devsy agent container setup
Agent -> ContainerAgent: devsy agent container credentials-server
alt if EXIT_AFTER_TIMEOUT
Agent -> ContainerAgent: devsy agent container daemon
end

alt if pro user
Agent -> ContainerAgent: devsy agent container setup-platform-access
ContainerAgent -> Platform: Setup pro
Platform --> ContainerAgent: platform creds
end

alt if GIT_SSH_SIGNATURE_FORWARDING
Agent -> Devsy: devsy agent git-credentials
Devsy --> Agent: git creds
end
alt if SSH_INJECT_DOCKER_CREDENTIALS
Agent -> Devsy: devsy agent docker-credentials
Devsy --> Agent: docker creds
end

Agent -> ContainerAgent: Run life cycle hooks

ContainerAgent --> Agent:
deactivate ContainerAgent
Agent --> Devsy:
deactivate Agent

alt if using browser based IDE (openvscode, jupyter)
Devsy -> ContainerAgent: devsy ssh --reuse-ssh-auth-sock
end

Devsy -> IDE: Start

alt if using normal IDE (vscode, intilliJ)
IDE -> ContainerAgent: devsy ssh
ContainerAgent --> IDE: ssh close
end

alt if using browser based IDE (openvscode, jupyter)
ContainerAgent -> Devsy: ssh close
end


@enduml
